# Analise exploratória dos microdados do Enem 2023

In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import textwrap
import warnings

pd.set_option('display.max_rows', None)

warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=UserWarning)

In [59]:
file_path = '../data/raw/MICRODADOS_ENEM_2023.csv'
# [Acessar fonte](https://download.inep.gov.br/microdados/microdados_enem_2023.zip) 

df_amostra = pd.read_csv(file_path, sep=';', encoding='latin1')
# aproximadamente 2m30s para rodar o dataset inteiro

#df_amostra = pd.read_csv(file_path, sep=';', encoding='latin1', nrows=10000)

In [60]:
df_amostra.head(20)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210059085136,2023,14,M,2,1,1,1,17,1,...,C,C,B,B,A,B,B,A,A,B
1,210059527735,2023,12,M,2,1,0,1,16,1,...,B,A,B,B,A,A,C,A,D,B
2,210061103945,2023,6,F,1,1,1,1,0,1,...,B,A,A,B,A,A,A,A,A,B
3,210060214087,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,D,A,A,B
4,210059980948,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,A
5,210058061539,2023,6,F,1,3,1,1,0,1,...,B,A,A,B,A,A,C,A,A,B
6,210059855122,2023,11,F,1,3,1,1,12,1,...,B,A,A,B,A,B,B,A,A,B
7,210058387333,2023,11,M,1,3,1,1,12,1,...,B,A,A,A,A,A,B,A,B,B
8,210059085137,2023,5,F,1,2,1,1,1,1,...,B,A,A,B,A,A,C,A,A,B
9,210060801601,2023,11,M,1,1,1,1,8,1,...,B,A,B,C,B,A,C,A,B,B
10,210059085130,2023,8,M,1,3,1,1,5,1,...,B,A,B,B,A,A,E,A,B,B
11,210060801595,2023,3,M,1,3,4,2,0,2,...,A,A,A,B,A,A,B,A,B,B
12,210059527729,2023,6,M,1,3,1,2,0,2,...,A,A,A,B,A,A,D,A,B,B
13,210060214081,2023,3,F,1,1,1,1,1,1,...,B,A,A,B,A,A,C,A,B,B
14,210059388087,2023,11,F,1,2,1,1,7,1,...,A,A,A,B,A,A,C,A,A,B
15,210059980942,2023,7,F,1,3,1,1,4,1,...,A,A,A,B,A,A,D,A,B,B
16,210058061534,2023,4,F,1,1,1,2,0,2,...,A,A,A,B,A,A,D,B,A,B
17,210059855117,2023,11,F,1,1,1,1,10,1,...,B,A,A,B,A,A,B,A,A,A
18,210058387328,2023,11,M,1,1,1,1,8,1,...,B,A,A,B,A,A,C,A,C,B
19,210059085131,2023,11,M,1,1,1,1,10,1,...,B,A,A,C,A,A,D,A,B,B

## Especificações do dataset
- Estudar dimensionalidade do dataset
- Estudar preliminarmente a natureza das features
- Buscar por valores vazios

In [61]:
print(f"O dataset possui {df_amostra.shape[0]} linhas e {df_amostra.shape[1]} colunas.\n")

O dataset possui 3933955 linhas e 76 colunas.

In [62]:
df_amostra.dtypes.value_counts()

str        37
float64    21
int64      18
Name: count, dtype: int64

In [63]:
df_amostra.info()

<class 'pandas.DataFrame'>
RangeIndex: 3933955 entries, 0 to 3933954
Data columns (total 76 columns):
 #   Column                  Dtype
---  ------                  -----
 0   NU_INSCRICAO            int64
 1   NU_ANO                  int64
 2   TP_FAIXA_ETARIA         int64
 3   TP_SEXO                 str
 4   TP_ESTADO_CIVIL         int64
 5   TP_COR_RACA             int64
 6   TP_NACIONALIDADE        int64
 7   TP_ST_CONCLUSAO         int64
 8   TP_ANO_CONCLUIU         int64
 9   TP_ESCOLA               int64
 10  TP_ENSINO               float64
 11  IN_TREINEIRO            int64
 12  CO_MUNICIPIO_ESC        float64
 13  NO_MUNICIPIO_ESC        str
 14  CO_UF_ESC               float64
 15  SG_UF_ESC               str
 16  TP_DEPENDENCIA_ADM_ESC  float64
 17  TP_LOCALIZACAO_ESC      float64
 18  TP_SIT_FUNC_ESC         float64
 19  CO_MUNICIPIO_PROVA      int64
 20  NO_MUNICIPIO_PROVA      str
 21  CO_UF_PROVA             int64
 22  SG_UF_PROVA             str
 23  TP_PRESENCA_CN          int64
 24  TP_PRESENCA_CH          int64
 25  TP_PRESENCA_LC          int64
 26  TP_PRESENCA_MT          int64
 27  CO_PROVA_CN             float64
 28  CO_PROVA_CH             float64
 29  CO_PROVA_LC             float64
 30  CO_PROVA_MT             float64
 31  NU_NOTA_CN              float64
 32  NU_NOTA_CH              float64
 33  NU_NOTA_LC              float64
 34  NU_NOTA_MT              float64
 35  TX_RESPOSTAS_CN         str
 36  TX_RESPOSTAS_CH         str
 37  TX_RESPOSTAS_LC         str
 38  TX_RESPOSTAS_MT         str
 39  TP_LINGUA               int64
 40  TX_GABARITO_CN          str
 41  TX_GABARITO_CH          str
 42  TX_GABARITO_LC          str
 43  TX_GABARITO_MT          str
 44  TP_STATUS_REDACAO       float64
 45  NU_NOTA_COMP1           float64
 46  NU_NOTA_COMP2           float64
 47  NU_NOTA_COMP3           float64
 48  NU_NOTA_COMP4           float64
 49  NU_NOTA_COMP5           float64
 50  NU_NOTA_REDACAO         float64
 51  Q001                    str
 52  Q002                    str
 53  Q003                    str
 54  Q004                    str
 55  Q005                    int64
 56  Q006                    str
 57  Q007                    str
 58  Q008                    str
 59  Q009                    str
 60  Q010                    str
 61  Q011                    str
 62  Q012                    str
 63  Q013                    str
 64  Q014                    str
 65  Q015                    str
 66  Q016                    str
 67  Q017                    str
 68  Q018                    str
 69  Q019                    str
 70  Q020                    str
 71  Q021                    str
 72  Q022                    str
 73  Q023                    str
 74  Q024                    str
 75  Q025                    str
dtypes: float64(21), int64(18), str(37)
memory usage: 2.2 GB

In [64]:
nulos = df_amostra.isnull().sum().sort_values(ascending=False)
percentual = (nulos / len(df_amostra)) * 100

pd.DataFrame({
    "nulos": nulos,
    "%": percentual
})

                          nulos          %
SG_UF_ESC               2975449  75.635054
CO_UF_ESC               2975449  75.635054
NO_MUNICIPIO_ESC        2975449  75.635054
CO_MUNICIPIO_ESC        2975449  75.635054
TP_LOCALIZACAO_ESC      2975449  75.635054
TP_SIT_FUNC_ESC         2975449  75.635054
TP_DEPENDENCIA_ADM_ESC  2975449  75.635054
TP_ENSINO               2594874  65.960948
CO_PROVA_CN             1241528  31.559283
TX_GABARITO_MT          1241528  31.559283
TX_RESPOSTAS_MT         1241528  31.559283
TX_RESPOSTAS_CN         1241528  31.559283
CO_PROVA_MT             1241528  31.559283
NU_NOTA_MT              1241528  31.559283
NU_NOTA_CN              1241528  31.559283
TX_GABARITO_CN          1241528  31.559283
NU_NOTA_CH              1111312  28.249230
NU_NOTA_LC              1111312  28.249230
CO_PROVA_LC             1111312  28.249230
TP_STATUS_REDACAO       1111312  28.249230
NU_NOTA_COMP3           1111312  28.249230
NU_NOTA_REDACAO         1111312  28.249230
NU_NOTA_COMP5           1111312  28.249230
TX_RESPOSTAS_CH         1111312  28.249230
TX_GABARITO_CH          1111312  28.249230
TX_RESPOSTAS_LC         1111312  28.249230
TX_GABARITO_LC          1111312  28.249230
CO_PROVA_CH             1111312  28.249230
NU_NOTA_COMP1           1111312  28.249230
NU_NOTA_COMP2           1111312  28.249230
NU_NOTA_COMP4           1111312  28.249230
TP_ANO_CONCLUIU               0   0.000000
IN_TREINEIRO                  0   0.000000
TP_ESCOLA                     0   0.000000
TP_ESTADO_CIVIL               0   0.000000
TP_SEXO                       0   0.000000
NU_ANO                        0   0.000000
TP_FAIXA_ETARIA               0   0.000000
NU_INSCRICAO                  0   0.000000
TP_ST_CONCLUSAO               0   0.000000
TP_COR_RACA                   0   0.000000
TP_NACIONALIDADE              0   0.000000
TP_PRESENCA_MT                0   0.000000
CO_MUNICIPIO_PROVA            0   0.000000
TP_LINGUA                     0   0.000000
NO_MUNICIPIO_PROVA            0   0.000000
SG_UF_PROVA                   0   0.000000
CO_UF_PROVA                   0   0.000000
TP_PRESENCA_CN                0   0.000000
TP_PRESENCA_CH                0   0.000000
TP_PRESENCA_LC                0   0.000000
Q001                          0   0.000000
Q002                          0   0.000000
Q003                          0   0.000000
Q004                          0   0.000000
Q005                          0   0.000000
Q006                          0   0.000000
Q007                          0   0.000000
Q008                          0   0.000000
Q009                          0   0.000000
Q010                          0   0.000000
Q011                          0   0.000000
Q012                          0   0.000000
Q013                          0   0.000000
Q014                          0   0.000000
Q015                          0   0.000000
Q016                          0   0.000000
Q017                          0   0.000000
Q018                          0   0.000000
Q019                          0   0.000000
Q020                          0   0.000000
Q021                          0   0.000000
Q022                          0   0.000000
Q023                          0   0.000000
Q024                          0   0.000000
Q025                          0   0.000000

## Construção do Dicionário de Dados

Será conduzido uma analise acerda das características de cada feature do dataset. 

O arquivo `resources/Dicionário_Microdados_Enem_2023.xlsx` representa o dicionário de dados oficial publicado juntamente ao dataset. A contrução do dicionário de dados neste nootebook será guiado por meio do dicionário oficial.

In [65]:
dados_dicionario = []

for coluna in df_amostra.columns:
    tipo = df_amostra[coluna].dtype
    valores_unicos = df_amostra[coluna].dropna().unique()
    
    # Pega até 5 exemplos de valores distintos
    exemplos = [str(v) for v in valores_unicos[:5]]
    
    dados_dicionario.append({
        'Nome da Variável': coluna,
        'Tipo de Dado': str(tipo),
        'Qtd Nulos': df_amostra[coluna].isnull().sum(),
        'Total Únicos': len(valores_unicos),
        'Exemplos Práticos': " | ".join(exemplos)
    })

df_dicionario = pd.DataFrame(dados_dicionario)

pd.set_option('display.max_rows', 150)
df_dicionario

,Nome da Variável,Tipo de Dado,Qtd Nulos,Total Únicos,Exemplos Práticos
0,NU_INSCRICAO,int64,0,3933955,210059085136 | 210059527735 | 210061103945 | 2...
1,NU_ANO,int64,0,1,2023
2,TP_FAIXA_ETARIA,int64,0,20,14 | 12 | 6 | 2 | 3
3,TP_SEXO,str,0,2,M | F
4,TP_ESTADO_CIVIL,int64,0,5,2 | 1 | 0 | 3 | 4
5,TP_COR_RACA,int64,0,6,1 | 3 | 2 | 0 | 5
6,TP_NACIONALIDADE,int64,0,5,1 | 0 | 4 | 2 | 3
7,TP_ST_CONCLUSAO,int64,0,4,1 | 2 | 3 | 4
8,TP_ANO_CONCLUIU,int64,0,18,17 | 16 | 0 | 12 | 1
9,TP_ESCOLA,int64,0,3,1 | 2 | 3
10,TP_ENSINO,float64,2594874,2,1.0 | 2.0
11,IN_TREINEIRO,int64,0,2,0 | 1
12,CO_MUNICIPIO_ESC,float64,2975449,5528,2304400.0 | 2311306.0 | 4128005.0 | 2910800.0 ...
13,NO_MUNICIPIO_ESC,str,2975449,5261,Fortaleza | Quixadá | Ubiratã | Feira de Santa...
14,CO_UF_ESC,float64,2975449,27,23.0 | 41.0 | 29.0 | 15.0 | 35.0
15,SG_UF_ESC,str,2975449,27,CE | PR | BA | PA | SP
16,TP_DEPENDENCIA_ADM_ESC,float64,2975449,4,2.0 | 1.0 | 3.0 | 4.0
17,TP_LOCALIZACAO_ESC,float64,2975449,2,1.0 | 2.0
18,TP_SIT_FUNC_ESC,float64,2975449,4,1.0 | 4.0 | 2.0 | 3.0
19,CO_MUNICIPIO_PROVA,int64,0,1750,5300108 | 4305108 | 2304400 | 2311306 | 2913606
20,NO_MUNICIPIO_PROVA,str,0,1715,Brasília | Caxias do Sul | Fortaleza | Quixadá...
21,CO_UF_PROVA,int64,0,27,53 | 43 | 23 | 29 | 26
22,SG_UF_PROVA,str,0,27,DF | RS | CE | BA | PE
23,TP_PRESENCA_CN,int64,0,3,0 | 1 | 2
24,TP_PRESENCA_CH,int64,0,3,0 | 1 | 2
25,TP_PRESENCA_LC,int64,0,3,0 | 1 | 2
26,TP_PRESENCA_MT,int64,0,3,0 | 1 | 2
27,CO_PROVA_CN,float64,1241528,13,1221.0 | 1224.0 | 1222.0 | 1223.0 | 1302.0
28,CO_PROVA_CH,float64,1111312,13,1193.0 | 1192.0 | 1191.0 | 1194.0 | 1198.0
29,CO_PROVA_LC,float64,1111312,13,1204.0 | 1202.0 | 1201.0 | 1203.0 | 1208.0
30,CO_PROVA_MT,float64,1241528,13,1211.0 | 1214.0 | 1212.0 | 1213.0 | 1292.0
31,NU_NOTA_CN,float64,1241528,5037,502.0 | 459.0 | 402.5 | 564.7 | 644.9
32,NU_NOTA_CH,float64,1111312,4812,498.9 | 508.5 | 379.2 | 630.3 | 620.2
33,NU_NOTA_LC,float64,1111312,4761,475.6 | 507.2 | 446.9 | 610.4 | 626.9
34,NU_NOTA_MT,float64,1241528,6058,363.2 | 466.7 | 338.3 | 680.2 | 736.3
35,TX_RESPOSTAS_CN,str,1241528,2675115,DBEBDCECCBCEBBBBDBABDDBBAABCBACDBACECCBAADEBB ...
36,TX_RESPOSTAS_CH,str,1111312,2814295,ABDEADAADCDABDCADAEABCDDCBAADCCBEBCEBEBDBEAED ...
37,TX_RESPOSTAS_LC,str,1111312,2819954,ACEBDCABAACAEBAECEBBBAAECBBDEADCAECCCEDDABEED ...
38,TX_RESPOSTAS_MT,str,1241528,2673883,CEAEACCCDABCDAACEDDBAAEBABDDEEBDAECABDBCBCADE ...
39,TP_LINGUA,int64,0,2,0 | 1
40,TX_GABARITO_CN,str,1241528,10,DBEABDABDCACDBECDDDBCAAABBACCCADEBECCCEDAEEED ...
41,TX_GABARITO_CH,str,1111312,8,ACEEABAADCDAADEABCDABCDCABCBDADEBAECABADBCDAE ...
42,TX_GABARITO_LC,str,1111312,9,DBABBAEBAAAACDACDEDAACADBADBCCEACCCEAAECBBEBCA...
43,TX_GABARITO_MT,str,1241528,8,BCCDEEABCBEDCEABBEBDABDDADDADECAADDCCBEBEABCC ...
44,TP_STATUS_REDACAO,float64,1111312,8,1.0 | 6.0 | 4.0 | 8.0 | 3.0
45,NU_NOTA_COMP1,float64,1111312,11,140.0 | 120.0 | 160.0 | 100.0 | 180.0
46,NU_NOTA_COMP2,float64,1111312,10,200.0 | 120.0 | 180.0 | 160.0 | 140.0
47,NU_NOTA_COMP3,float64,1111312,12,100.0 | 160.0 | 120.0 | 180.0 | 140.0
48,NU_NOTA_COMP4,float64,1111312,11,120.0 | 180.0 | 160.0 | 100.0 | 200.0
49,NU_NOTA_COMP5,float64,1111312,11,140.0 | 200.0 | 80.0 | 120.0 | 180.0
50,NU_NOTA_REDACAO,float64,1111312,50,700.0 | 880.0 | 560.0 | 600.0 | 860.0
51,Q001,str,0,8,A | F | H | D | B
52,Q002,str,0,8,F | E | D | B | C
53,Q003,str,0,6,E | C | B | A | D
54,Q004,str,0,6,D | B | F | A | E
55,Q005,int64,0,20,5 | 3 | 4 | 1 | 2
56,Q006,str,0,17,F | H | C | B | A
57,Q007,str,0,4,C | A | B | D
58,Q008,str,0,5,C | B | D | A | E
59,Q009,str,0,5,D | C | B | A | E
60,Q010,str,0,5,C | B | A | D | E
61,Q011,str,0,5,D | A | B | C | E
62,Q012,str,0,5,C | B | A | E | D
63,Q013,str,0,5,B | A | C | D | E
64,Q014,str,0,5,B | A | C | E | D
65,Q015,str,0,5,D | A | B | C | E
66,Q016,str,0,5,C | B | A | D | E
67,Q017,str,0,5,C | A | B | D | E
68,Q018,str,0,2,B | A
69,Q019,str,0,5,B | A | C | D | E
70,Q020,str,0,2,A | B
71,Q021,str,0,2,B | A
72,Q022,str,0,5,B | C | A | D | E
73,Q023,str,0,2,A | B
74,Q024,str,0,5,A | D | B | C | E
75,Q025,str,0,2,B | A

Após comparar o dicionário acima com o dicionário oficial, não foi encontrado divergências.

## Limpeza inicial dos dados
Antes de analisar mais de perto as fetures do dataset, será feito uma limpeza de dados inicial, dado os objetivos deste experimento e os insights propiciados pelo estudo inicial das colunas.

In [68]:
df = df_amostra.copy()

In [69]:
# exclusão das instâncias que representam candidados treineiros
n_treineiros = len(df[df['IN_TREINEIRO'] == 1])

df = df[df['IN_TREINEIRO'] == 0]
print("Instancias deletadas: ", n_treineiros)

Instancias deletadas:  620067

In [70]:
# exclusão das instâncias que representam candidados que faltaram em 1 ou mais provas
colunas_presenca = ['TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT']
n_ausentes = len(df[(df[colunas_presenca] != 1).any(axis=1)])

df = df[(df[colunas_presenca] == 1).all(axis=1)]
print("Instancias deletadas: ", n_ausentes)

Instancias deletadas:  1147045

In [71]:
colunas_excluir = [
# colunas com alta porcentagem de valores nulos (>65%)
"SG_UF_ESC", "CO_UF_ESC", "NO_MUNICIPIO_ESC", "CO_MUNICIPIO_ESC", "TP_LOCALIZACAO_ESC", "TP_SIT_FUNC_ESC", "TP_DEPENDENCIA_ADM_ESC", "TP_ENSINO",

# informações não relevantes para a analise
"NU_INSCRICAO", "IN_TREINEIRO",  "TP_SIT_FUNC_ESC", "TP_PRESENCA_CN", "TP_PRESENCA_CH", "TP_PRESENCA_LC", "TP_PRESENCA_MT", "CO_PROVA_CN", "CO_PROVA_CH", "CO_PROVA_LC", "CO_PROVA_MT", "NO_MUNICIPIO_PROVA", "CO_UF_PROVA",

# respostas do canditado e gabatito (uma vez que existe a nota calculada do candidato na base)
"TX_RESPOSTAS_CN", "TX_RESPOSTAS_CH", "TX_RESPOSTAS_LC", "TX_RESPOSTAS_MT", "TX_GABARITO_CN", "TX_GABARITO_CH", "TX_GABARITO_LC", "TX_GABARITO_MT",

# detalhes sobre a avaliação da redação 
# (serão removidos pois o experimento visa analisar de forma macro o desempenho do estudante, sendo apenas a nota final da redação o suficiente)
"TP_STATUS_REDACAO", "NU_NOTA_COMP1", "NU_NOTA_COMP2", "NU_NOTA_COMP3", "NU_NOTA_COMP4", "NU_NOTA_COMP5",
]

df = df.drop(colunas_excluir, axis=1)

In [72]:
df.columns

Index(['NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESTADO_CIVIL',
       'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU',
       'TP_ESCOLA', 'CO_MUNICIPIO_PROVA', 'SG_UF_PROVA', 'NU_NOTA_CN',
       'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'TP_LINGUA',
       'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006',
       'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015',
       'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024',
       'Q025'],
      dtype='str')

In [ ]:
total_linhas_com_nulos = df.isnull().any(axis=1).sum()

print(f"Total de instâncias com pelo menos um valor nulo: {total_linhas_com_nulos}")

Total de instâncias com pelo menos um valor nulo: 0
Isso representa 0.00% do dataset.

In [77]:
print(f"O dataset original possui {df_amostra.shape[0]} linhas e {df_amostra.shape[1]} colunas.\n")
print(f"O dataset modificado possui {df.shape[0]} linhas e {df.shape[1]} colunas.\n")

O dataset original possui 3933955 linhas e 76 colunas.

O dataset modificado possui 2166843 linhas e 42 colunas.

In [ ]:
df.to_csv('..data/processed/df_limpo.csv', index=False)