# Analise exploratória dos microdados do Enem 2023

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [2]:
file_path = '../data/raw/MICRODADOS_ENEM_2023.csv'
# [Acessar fonte](https://download.inep.gov.br/microdados/microdados_enem_2023.zip) 

df_amostra = pd.read_csv(file_path, sep=';', encoding='latin1')
# aproximadamente 2m30s para rodar o dataset inteiro

# df_amostra = pd.read_csv(file_path, sep=';', encoding='latin1', nrow=1000)

In [3]:
df_amostra.head(20);

## Especificações do dataset
- Estudar dimensionalidade do dataset
- Estudar preliminarmente a natureza das features
- Buscar por valores vazios

In [4]:
print(f"O dataset possui {df_amostra.shape[0]} linhas e {df_amostra.shape[1]} colunas.\n")

O dataset possui 3933955 linhas e 76 colunas.

In [ ]:
df_amostra.dtypes.value_counts()

Visualizando os tipos de dados de cada variável:

NU_INSCRICAO       int64
NU_ANO             int64
TP_FAIXA_ETARIA    int64
TP_SEXO              str
TP_ESTADO_CIVIL    int64
                   ...
Q021                 str
Q022                 str
Q023                 str
Q024                 str
Q025                 str
Length: 76, dtype: object

In [ ]:
df_amostra.info()

Visualizando especificações numéricas do dataset:

<bound method DataFrame.info of          NU_INSCRICAO  NU_ANO  TP_FAIXA_ETARIA TP_SEXO  TP_ESTADO_CIVIL  \
0        210059085136    2023               14       M                2
1        210059527735    2023               12       M                2
2        210061103945    2023                6       F                1
3        210060214087    2023                2       F                1
4        210059980948    2023                3       F                1
...               ...     ...              ...     ...              ...
3933950  210061959676    2023               12       M                1
3933951  210061950911    2023                1       F                1
3933952  210061965966    2023                3       F                1
3933953  210061932304    2023                2       M                1
3933954  210058924455    2023                3       F                1

         TP_COR_RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  \
0                  1                 1                1               17
1                  1                 0                1               16
2                  1                 1                1                0
3                  3                 1                2                0
4                  3                 1                2                0
...              ...               ...              ...              ...
3933950            1                 1                1                6
3933951            1                 2                3                0
3933952            3                 1                2                0
3933953            1                 1                2                0
3933954            3                 1                2                0

         TP_ESCOLA  ...  Q016  Q017  Q018 Q019  Q020 Q021  Q022  Q023  Q024  \
0                1  ...     C     C     B    B     A    B     B     A     A
1                1  ...     B     A     B    B     A    A     C     A     D
2                1  ...     B     A     A    B     A    A     A     A     A
3                2  ...     A     A     A    B     A    A     D     A     A
4                2  ...     A     A     A    B     A    A     B     A     A
...            ...  ...   ...   ...   ...  ...   ...  ...   ...   ...   ...
3933950          1  ...     B     A     A    C     A    B     E     A     A
3933951          1  ...     B     A     B    C     B    B     B     B     C
3933952          2  ...     A     A     A    B     A    A     B     A     A
3933953          3  ...     B     B     B    C     A    A     D     A     C
3933954          2  ...     A     A     A    B     B    A     D     A     B

         Q025
0           B
1           B
2           B
3           B
4           A
...       ...
3933950     B
3933951     B
3933952     B
3933953     B
3933954     B

[3933955 rows x 76 columns]>

In [ ]:
df_amostra.describe().T

### Construção do Dicionário de Dados

Será conduzido uma analise acerda das características de cada feature do dataset. 

O arquivo `resources/Dicionário_Microdados_Enem_2023.xlsx` representa o dicionário de dados oficial publicado juntamente ao dataset. A contrução do dicionário de dados neste nootebook será guiado por meio do dicionário oficial.

In [7]:
dados_dicionario = []

for coluna in df_amostra.columns:
    tipo = df_amostra[coluna].dtype
    valores_unicos = df_amostra[coluna].dropna().unique()
    
    # Pega até 5 exemplos de valores distintos
    exemplos = [str(v) for v in valores_unicos[:5]]
    
    dados_dicionario.append({
        'Nome da Variável': coluna,
        'Tipo de Dado': str(tipo),
        'Qtd Nulos': df_amostra[coluna].isnull().sum(),
        'Total Únicos': len(valores_unicos),
        'Exemplos Práticos': " | ".join(exemplos)
    })

df_dicionario = pd.DataFrame(dados_dicionario)

pd.set_option('display.max_rows', 150)
df_dicionario

,Nome da Variável,Tipo de Dado,Qtd Nulos,Total Únicos,Exemplos Práticos
0,NU_INSCRICAO,int64,0,3933955,210059085136 | 210059527735 | 210061103945 | 2...
1,NU_ANO,int64,0,1,2023
2,TP_FAIXA_ETARIA,int64,0,20,14 | 12 | 6 | 2 | 3
3,TP_SEXO,str,0,2,M | F
4,TP_ESTADO_CIVIL,int64,0,5,2 | 1 | 0 | 3 | 4
5,TP_COR_RACA,int64,0,6,1 | 3 | 2 | 0 | 5
6,TP_NACIONALIDADE,int64,0,5,1 | 0 | 4 | 2 | 3
7,TP_ST_CONCLUSAO,int64,0,4,1 | 2 | 3 | 4
8,TP_ANO_CONCLUIU,int64,0,18,17 | 16 | 0 | 12 | 1
9,TP_ESCOLA,int64,0,3,1 | 2 | 3
10,TP_ENSINO,float64,2594874,2,1.0 | 2.0
11,IN_TREINEIRO,int64,0,2,0 | 1
12,CO_MUNICIPIO_ESC,float64,2975449,5528,2304400.0 | 2311306.0 | 4128005.0 | 2910800.0 ...
13,NO_MUNICIPIO_ESC,str,2975449,5261,Fortaleza | Quixadá | Ubiratã | Feira de Santa...
14,CO_UF_ESC,float64,2975449,27,23.0 | 41.0 | 29.0 | 15.0 | 35.0
15,SG_UF_ESC,str,2975449,27,CE | PR | BA | PA | SP
16,TP_DEPENDENCIA_ADM_ESC,float64,2975449,4,2.0 | 1.0 | 3.0 | 4.0
17,TP_LOCALIZACAO_ESC,float64,2975449,2,1.0 | 2.0
18,TP_SIT_FUNC_ESC,float64,2975449,4,1.0 | 4.0 | 2.0 | 3.0
19,CO_MUNICIPIO_PROVA,int64,0,1750,5300108 | 4305108 | 2304400 | 2311306 | 2913606
20,NO_MUNICIPIO_PROVA,str,0,1715,Brasília | Caxias do Sul | Fortaleza | Quixadá...
21,CO_UF_PROVA,int64,0,27,53 | 43 | 23 | 29 | 26
22,SG_UF_PROVA,str,0,27,DF | RS | CE | BA | PE
23,TP_PRESENCA_CN,int64,0,3,0 | 1 | 2
24,TP_PRESENCA_CH,int64,0,3,0 | 1 | 2
25,TP_PRESENCA_LC,int64,0,3,0 | 1 | 2
26,TP_PRESENCA_MT,int64,0,3,0 | 1 | 2
27,CO_PROVA_CN,float64,1241528,13,1221.0 | 1224.0 | 1222.0 | 1223.0 | 1302.0
28,CO_PROVA_CH,float64,1111312,13,1193.0 | 1192.0 | 1191.0 | 1194.0 | 1198.0
29,CO_PROVA_LC,float64,1111312,13,1204.0 | 1202.0 | 1201.0 | 1203.0 | 1208.0
30,CO_PROVA_MT,float64,1241528,13,1211.0 | 1214.0 | 1212.0 | 1213.0 | 1292.0
31,NU_NOTA_CN,float64,1241528,5037,502.0 | 459.0 | 402.5 | 564.7 | 644.9
32,NU_NOTA_CH,float64,1111312,4812,498.9 | 508.5 | 379.2 | 630.3 | 620.2
33,NU_NOTA_LC,float64,1111312,4761,475.6 | 507.2 | 446.9 | 610.4 | 626.9
34,NU_NOTA_MT,float64,1241528,6058,363.2 | 466.7 | 338.3 | 680.2 | 736.3
35,TX_RESPOSTAS_CN,str,1241528,2675115,DBEBDCECCBCEBBBBDBABDDBBAABCBACDBACECCBAADEBB ...
36,TX_RESPOSTAS_CH,str,1111312,2814295,ABDEADAADCDABDCADAEABCDDCBAADCCBEBCEBEBDBEAED ...
37,TX_RESPOSTAS_LC,str,1111312,2819954,ACEBDCABAACAEBAECEBBBAAECBBDEADCAECCCEDDABEED ...
38,TX_RESPOSTAS_MT,str,1241528,2673883,CEAEACCCDABCDAACEDDBAAEBABDDEEBDAECABDBCBCADE ...
39,TP_LINGUA,int64,0,2,0 | 1
40,TX_GABARITO_CN,str,1241528,10,DBEABDABDCACDBECDDDBCAAABBACCCADEBECCCEDAEEED ...
41,TX_GABARITO_CH,str,1111312,8,ACEEABAADCDAADEABCDABCDCABCBDADEBAECABADBCDAE ...
42,TX_GABARITO_LC,str,1111312,9,DBABBAEBAAAACDACDEDAACADBADBCCEACCCEAAECBBEBCA...
43,TX_GABARITO_MT,str,1241528,8,BCCDEEABCBEDCEABBEBDABDDADDADECAADDCCBEBEABCC ...
44,TP_STATUS_REDACAO,float64,1111312,8,1.0 | 6.0 | 4.0 | 8.0 | 3.0
45,NU_NOTA_COMP1,float64,1111312,11,140.0 | 120.0 | 160.0 | 100.0 | 180.0
46,NU_NOTA_COMP2,float64,1111312,10,200.0 | 120.0 | 180.0 | 160.0 | 140.0
47,NU_NOTA_COMP3,float64,1111312,12,100.0 | 160.0 | 120.0 | 180.0 | 140.0
48,NU_NOTA_COMP4,float64,1111312,11,120.0 | 180.0 | 160.0 | 100.0 | 200.0
49,NU_NOTA_COMP5,float64,1111312,11,140.0 | 200.0 | 80.0 | 120.0 | 180.0
50,NU_NOTA_REDACAO,float64,1111312,50,700.0 | 880.0 | 560.0 | 600.0 | 860.0
51,Q001,str,0,8,A | F | H | D | B
52,Q002,str,0,8,F | E | D | B | C
53,Q003,str,0,6,E | C | B | A | D
54,Q004,str,0,6,D | B | F | A | E
55,Q005,int64,0,20,5 | 3 | 4 | 1 | 2
56,Q006,str,0,17,F | H | C | B | A
57,Q007,str,0,4,C | A | B | D
58,Q008,str,0,5,C | B | D | A | E
59,Q009,str,0,5,D | C | B | A | E
60,Q010,str,0,5,C | B | A | D | E
61,Q011,str,0,5,D | A | B | C | E
62,Q012,str,0,5,C | B | A | E | D
63,Q013,str,0,5,B | A | C | D | E
64,Q014,str,0,5,B | A | C | E | D
65,Q015,str,0,5,D | A | B | C | E
66,Q016,str,0,5,C | B | A | D | E
67,Q017,str,0,5,C | A | B | D | E
68,Q018,str,0,2,B | A
69,Q019,str,0,5,B | A | C | D | E
70,Q020,str,0,2,A | B
71,Q021,str,0,2,B | A
72,Q022,str,0,5,B | C | A | D | E
73,Q023,str,0,2,A | B
74,Q024,str,0,5,A | D | B | C | E
75,Q025,str,0,2,B | A

Após comparar o dicionário acima com o dicionário oficial, não foi encontrado divergências.

### Classificação das features

Para facilitar as manipulações futuras, podemos separar as features em 4 grandes grupos, baseando-se em suas descrições no dicionário oficial:

1. **Dados Categóricos (Qualitativos):** 
   - São features que representam características, grupos ou códigos. 
   - Exemplo: `TP_FAIXA_ETARIA`.
   
2. **Dados Numéricos (Quantitativos Contínuos):**
   - São os valores que representam medidas ou grandezas contínuas.
   - Exemplo: `NU_NOTA_REDACAO`.

3. **Dados Textuais ("Escritos" ou Strings Literais):**
   - Dados que representam texto descritivo.
   - Exemplo: `NO_MUNICIPIO`, `TX_GABARITO`.
   
4. **Identificadores (Chave):**
   - Servem apenas como indexador ou identificador.
   - Exemplo: `NU_INSCRICAO`.

In [10]:
# Indentificadores 
colunas_identificadoras = ['NU_INSCRICAO', 'CO_MUNICIPIO_ESC', 'CO_MUNICIPIO_PROVA'] 

# Dados Numéricos 
colunas_numericas = [
    'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 
    'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4', 
    'NU_NOTA_COMP5', 'NU_NOTA_REDACAO'
]

# Dados Escritos / Textuais Liberais
colunas_textuais = [
    'NO_MUNICIPIO_ESC', 'SG_UF_ESC',
    'NO_MUNICIPIO_PROVA', 'SG_UF_PROVA',
    'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT',
    'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT'
]

# Dados Categóricos (o restante)
colunas_categoricas = [
    col for col in df_amostra.columns 
    if col not in colunas_numericas and col not in colunas_textuais and col not in colunas_identificadoras
]

In [ ]:
dicionario_categorico = {}

for coluna in colunas_categoricas:
    valores_unicos = df_amostra[coluna].dropna().unique()
    contagem = df_amostra[coluna].value_counts().sort_index()
    
    dicionario_categorico[coluna] = {
        'Qtd_Valores_Unicos': len(valores_unicos),
        'Qtd_Nulos': df_amostra[coluna].isnull().sum(),
        'Valores': contagem.to_dict()
    }

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Criar um DataFrame resumido para visualização
resumo_categorico = []
for coluna, dados in dicionario_categorico.items():
    resumo_categorico.append({
        'Coluna': coluna,
        'Qtd_Valores_Únicos': dados['Qtd_Valores_Unicos'],
        'Qtd_Nulos': dados['Qtd_Nulos'],
        'Valores': str(dados['Valores'])
    })

df_resumo = pd.DataFrame(resumo_categorico)
display(df_resumo)

,Coluna,Qtd_Valores_Únicos,Qtd_Nulos,Valores
0,NU_ANO,1,0,{2023: 3933955}
1,TP_FAIXA_ETARIA,20,0,"{1: 347434, 2: 753800, 3: 905047, 4: 431592, 5: 267383, 6: 183401, 7: 137884, 8: 111813, 9: 91359, 10: 73127, 11: 246292, 12: 133381, 13: 96927, 14: 67135, 15: 40791, 16: 24619, 17: 13439, 18: 5503, 19: 2161, 20: 867}"
2,TP_SEXO,2,0,"{'F': 2411185, 'M': 1522770}"
3,TP_ESTADO_CIVIL,5,0,"{0: 171900, 1: 3491857, 2: 200456, 3: 64933, 4: 4809}"
4,TP_COR_RACA,6,0,"{0: 52575, 1: 1575848, 2: 509511, 3: 1706798, 4: 64512, 5: 24711}"
5,TP_NACIONALIDADE,5,0,"{0: 2153, 1: 3842681, 2: 73429, 3: 7112, 4: 8580}"
6,TP_ST_CONCLUSAO,4,0,"{1: 1895301, 2: 1401164, 3: 620067, 4: 17423}"
7,TP_ANO_CONCLUIU,18,0,"{0: 2243134, 1: 418530, 2: 264183, 3: 149798, 4: 136449, 5: 104195, 6: 85411, 7: 65549, 8: 54769, 9: 46654, 10: 39920, 11: 35512, 12: 29001, 13: 27421, 14: 24639, 15: 20998, 16: 20471, 17: 167321}"
8,TP_ESCOLA,3,0,"{1: 2532796, 2: 1166540, 3: 234619}"
9,TP_ENSINO,2,2594874,"{1.0: 1332195, 2.0: 6886}"
10,IN_TREINEIRO,2,0,"{0: 3313888, 1: 620067}"
11,CO_UF_ESC,27,2975449,"{11.0: 10209, 12.0: 4111, 13.0: 26557, 14.0: 2277, 15.0: 35212, 16.0: 4240, 17.0: 7336, 21.0: 31877, 22.0: 18393, 23.0: 98595, 24.0: 16776, 25.0: 24870, 26.0: 44881, 27.0: 20934, 28.0: 10277, 29.0: 43453, 31.0: 66972, 32.0: 20626, 33.0: 63842, 35.0: 187067, 41.0: 54226, 42.0: 31480, 43.0: 39700, 50.0: 11894, 51.0: 16792, 52.0: 45796, 53.0: 20113}"
12,TP_DEPENDENCIA_ADM_ESC,4,2975449,"{1.0: 48433, 2.0: 671488, 3.0: 8957, 4.0: 229628}"
13,TP_LOCALIZACAO_ESC,2,2975449,"{1.0: 922856, 2.0: 35650}"
14,TP_SIT_FUNC_ESC,4,2975449,"{1.0: 950936, 2.0: 3182, 3.0: 507, 4.0: 3881}"
15,CO_UF_PROVA,27,0,"{11: 36038, 12: 24274, 13: 92916, 14: 9639, 15: 229162, 16: 28807, 17: 32618, 21: 165756, 22: 99639, 23: 241960, 24: 100706, 25: 124511, 26: 218859, 27: 82760, 28: 65540, 29: 324268, 31: 358575, 32: 73724, 33: 282296, 35: 590767, 41: 166506, 42: 91263, 43: 159919, 50: 47455, 51: 63912, 52: 149110, 53: 72975}"
16,TP_PRESENCA_CN,3,0,"{0: 1239316, 1: 2692427, 2: 2212}"
17,TP_PRESENCA_CH,3,0,"{0: 1106714, 1: 2822643, 2: 4598}"
18,TP_PRESENCA_LC,3,0,"{0: 1106714, 1: 2822643, 2: 4598}"
19,TP_PRESENCA_MT,3,0,"{0: 1239316, 1: 2692427, 2: 2212}"
20,CO_PROVA_CN,13,1241528,"{1221.0: 668204, 1222.0: 668909, 1223.0: 674819, 1224.0: 669321, 1225.0: 3319, 1226.0: 646, 1227.0: 120, 1228.0: 673, 1229.0: 1212, 1301.0: 1297, 1302.0: 1293, 1303.0: 1313, 1304.0: 1301}"
21,CO_PROVA_CH,13,1111312,"{1191.0: 701099, 1192.0: 701475, 1193.0: 701519, 1194.0: 707167, 1195.0: 3471, 1196.0: 679, 1197.0: 125, 1198.0: 704, 1199.0: 1273, 1271.0: 1274, 1272.0: 1290, 1273.0: 1295, 1274.0: 1272}"
22,CO_PROVA_LC,13,1111312,"{1201.0: 701099, 1202.0: 701475, 1203.0: 707168, 1204.0: 701518, 1205.0: 3471, 1206.0: 679, 1207.0: 125, 1208.0: 704, 1209.0: 1273, 1281.0: 1274, 1282.0: 1290, 1283.0: 1272, 1284.0: 1295}"
23,CO_PROVA_MT,13,1241528,"{1211.0: 668204, 1212.0: 668909, 1213.0: 674819, 1214.0: 669321, 1215.0: 3319, 1216.0: 646, 1217.0: 120, 1218.0: 673, 1219.0: 1212, 1291.0: 1297, 1292.0: 1293, 1293.0: 1301, 1294.0: 1313}"
24,TP_LINGUA,2,0,"{0: 2136104, 1: 1797851}"
25,TP_STATUS_REDACAO,8,1111312,"{1.0: 2704814, 2.0: 2016, 3.0: 22505, 4.0: 55403, 6.0: 24466, 7.0: 1905, 8.0: 9091, 9.0: 2443}"
26,Q001,8,0,"{'A': 174712, 'B': 700175, 'C': 513213, 'D': 438139, 'E': 1114164, 'F': 333981, 'G': 256045, 'H': 403526}"
27,Q002,8,0,"{'A': 110831, 'B': 505525, 'C': 437022, 'D': 473854, 'E': 1377605, 'F': 455268, 'G': 441893, 'H': 131957}"
28,Q003,6,0,"{'A': 750778, 'B': 790173, 'C': 911756, 'D': 706775, 'E': 268192, 'F': 506281}"
29,Q004,6,0,"{'A': 608127, 'B': 1632671, 'C': 247158, 'D': 892420, 'E': 200584, 'F': 352995}"
30,Q005,20,0,"{1: 146875, 2: 567635, 3: 1086674, 4: 1247259, 5: 566325, 6: 194132, 7: 71049, 8: 29968, 9: 11192, 10: 6826, 11: 2281, 12: 1497, 13: 647, 14: 364, 15: 348, 16: 126, 17: 109, 18: 86, 19: 57, 20: 505}"
31,Q006,17,0,"{'A': 268053, 'B': 1245271, 'C': 650942, 'D': 437366, 'E': 293994, 'F': 171344, 'G': 261327, 'H': 139279, 'I': 85970, 'J': 75179, 'K': 59631, 'L': 39596, 'M': 33626, 'N': 41565, 'O': 41218, 'P': 38105, 'Q': 51489}"
32,Q007,4,0,"{'A': 3611179, 'B': 178524, 'C': 39882, 'D': 104370}"
33,Q008,5,0,"{'A': 37878, 'B': 2647503, 'C': 855720, 'D': 253087, 'E': 139767}"
34,Q009,5,0,"{'A': 34469, 'B': 560699, 'C': 1968685, 'D': 1167141, 'E': 202961}"
35,Q010,5,0,"{'A': 2167356, 'B': 1392596, 'C': 323334, 'D': 41185, 'E': 9484}"
36,Q011,5,0,"{'A': 2983690, 'B': 842923, 'C': 95329, 'D': 10022, 'E': 1991}"
37,Q012,5,0,"{'A': 75430, 'B': 3653942, 'C': 186456, 'D': 14986, 'E': 3141}"
38,Q013,5,0,"{'A': 2217219, 'B': 1580612, 'C': 117473, 'D': 15112, 'E': 3539}"
39,Q014,5,0,"{'A': 1517308, 'B': 2368207, 'C': 46133, 'D': 1863, 'E': 444}"
40,Q015,5,0,"{'A': 3438821, 'B': 488250, 'C': 6110, 'D': 501, 'E': 273}"
41,Q016,5,0,"{'A': 2064853, 'B': 1838403, 'C': 28698, 'D': 1515, 'E': 486}"
42,Q017,5,0,"{'A': 3803308, 'B': 127927, 'C': 2180, 'D': 280, 'E': 260}"
43,Q018,2,0,"{'A': 3032209, 'B': 901746}"
44,Q019,5,0,"{'A': 305208, 'B': 2607933, 'C': 661090, 'D': 241516, 'E': 118208}"
45,Q020,2,0,"{'A': 3430585, 'B': 503370}"
46,Q021,2,0,"{'A': 3100005, 'B': 833950}"
47,Q022,5,0,"{'A': 101584, 'B': 764861, 'C': 1087753, 'D': 1138368, 'E': 841389}"
48,Q023,2,0,"{'A': 3579617, 'B': 354338}"
49,Q024,5,0,"{'A': 2041637, 'B': 1362634, 'C': 341120, 'D': 126296, 'E': 62268}"
50,Q025,2,0,"{'A': 375504, 'B': 3558451}"

In [ ]:
n_cols = 2
n_rows = math.ceil(len(colunas_categoricas) / n_cols)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 5 * n_rows))
axes = axes.flatten()

for i, col in enumerate(colunas_categoricas):
    sns.countplot(
        data=df_amostra,
        x=col,
        order=df_amostra[col].value_counts().index,
        ax=axes[i]
    )
    
    axes[i].set_title(col)
    axes[i].tick_params(axis='x', rotation=45)

# remove eixos vazios
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()